default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  username: coms_admin
  database: coms_development

test:
  <<: *default
  username: coms_admin
  database: coms_test

production:
  <<: *default
  database: coms_production
