# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cd81745f39a7c1fb68fcd325de2cebaa9a6db939f65eb94b970d7c6037b1e9545284fbde3c1811415e548b70b40cf27fb4538435f7bb2d7d1286f2253c624b0

test:
  secret_key_base: db7a05fc47cd71f9538d49b07f82d18c56a702d3b61b7f65db487d1f368495c6c214ba2dc059773547209e1217f04d098dec2af148a30cd0c9384cf15651aaca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
